//! go2rtc is the single RTSP client per camera. Live viewers (MSE over
//! WebSocket, sub-second latency), HLS, recording and snapshots all read from
//! its loopback restream instead of opening their own sessions to the camera —
//! cheap cameras allow only a couple of concurrent RTSP sessions and drop
//! frames when that limit is hit.
//!
//! The backend owns the go2rtc process: it writes the config (streams come
//! from the camera table), spawns it, and respawns it when it dies or when the
//! camera set changes. Everything listens on 127.0.0.1 only; clients reach
//! go2rtc exclusively through the authenticated `/api/live` proxy.

use open_nvr_domain::entities::Camera;
use open_nvr_infrastructure::crypto::credentials::CredentialEncryptor;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;
use tokio::process::{Child, Command};
use tokio::sync::Mutex;
use tracing::{error, info, warn};
use uuid::Uuid;

pub const API_ADDR: &str = "127.0.0.1:1984";
pub const RTSP_ADDR: &str = "127.0.0.1:8554";

pub struct Go2Rtc {
    bin: PathBuf,
    config_path: PathBuf,
    log_path: PathBuf,
    encryptor: Option<CredentialEncryptor>,
    state: Mutex<ProcState>,
}

#[derive(Default)]
struct ProcState {
    child: Option<Child>,
    /// Hash of the config the running process was started with.
    config_hash: u64,
}

impl Go2Rtc {
    /// Returns `None` when no go2rtc binary is available; callers then fall
    /// back to talking to cameras directly.
    pub fn from_env(encryptor: Option<CredentialEncryptor>) -> Option<Self> {
        let bin = std::env::var("GO2RTC_BIN")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("./bin/go2rtc"));
        if !bin.is_file() {
            warn!(bin = %bin.display(), "go2rtc binary not found; live view falls back to HLS and cameras are read directly");
            return None;
        }

        let data_dir = PathBuf::from(std::env::var("GO2RTC_DATA_DIR").unwrap_or_else(|_| "./data".into()));
        std::fs::create_dir_all(&data_dir).ok();
        let log_dir = std::env::var("FFMPEG_LOG_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("/tmp/opennvr-ffmpeg-logs"));
        std::fs::create_dir_all(&log_dir).ok();

        info!(bin = %bin.display(), "go2rtc restreamer enabled");
        Some(Self {
            bin,
            config_path: data_dir.join("go2rtc.yaml"),
            log_path: log_dir.join("go2rtc.log"),
            encryptor,
            state: Mutex::new(ProcState::default()),
        })
    }

    /// Loopback RTSP URL that other local consumers should read from.
    pub fn rtsp_url(camera_id: Uuid) -> String {
        format!("rtsp://{}/{}", RTSP_ADDR, camera_id)
    }

    /// go2rtc stream name for a camera: the main stream, or its sub stream
    /// when one is configured and asked for.
    pub fn stream_name(camera: &Camera, sub: bool) -> String {
        if sub && camera.sub_stream_url.is_some() {
            format!("{}_sub", camera.id)
        } else {
            camera.id.to_string()
        }
    }

    /// Camera URL with decrypted credentials spliced in, unless the URL
    /// already carries its own.
    fn source_url(&self, camera: &Camera, url: &str) -> String {
        let (Some(enc), Some(blob)) = (&self.encryptor, &camera.credentials_encrypted) else {
            return url.to_string();
        };
        let Some((scheme, rest)) = url.split_once("://") else {
            return url.to_string();
        };
        let authority = rest.split('/').next().unwrap_or("");
        if authority.contains('@') {
            return url.to_string();
        }
        match enc.decrypt(blob) {
            Ok(creds) => match creds.split_once(':') {
                Some((user, pass)) => format!(
                    "{}://{}:{}@{}",
                    scheme,
                    percent_encode(user),
                    percent_encode(pass),
                    rest
                ),
                None => url.to_string(),
            },
            Err(e) => {
                warn!(camera_id = %camera.id, error = %e, "Cannot decrypt camera credentials");
                url.to_string()
            }
        }
    }

    fn render_config(&self, cameras: &[Camera]) -> String {
        let mut cfg = format!(
            "# Generated by open-nvr on every start; edits are overwritten.\n\
             log:\n  level: warn\n\
             api:\n  listen: \"{api}\"\n\
             rtsp:\n  listen: \"{rtsp}\"\n\
             webrtc:\n  listen: \"\"\n\
             rtmp:\n  listen: \"\"\n\
             srtp:\n  listen: \"\"\n\
             streams:\n",
            api = API_ADDR,
            rtsp = RTSP_ADDR,
        );
        let mut sorted: Vec<&Camera> = cameras.iter().collect();
        sorted.sort_by_key(|c| c.id);
        for cam in sorted {
            cfg.push_str(&format!("  \"{}\": {}\n", cam.id, yaml_str(&self.source_url(cam, &cam.stream_url))));
            if let Some(ref sub) = cam.sub_stream_url {
                cfg.push_str(&format!("  \"{}_sub\": {}\n", cam.id, yaml_str(&self.source_url(cam, sub))));
            }
        }
        cfg
    }

    /// Make sure go2rtc runs with streams for exactly `cameras`. Restarts the
    /// process when it died or when the camera set/URLs changed. Returns true
    /// if a (re)start happened, so callers can restart their own consumers.
    pub async fn ensure(&self, cameras: &[Camera]) -> bool {
        let config = self.render_config(cameras);
        let mut hasher = DefaultHasher::new();
        config.hash(&mut hasher);
        let hash = hasher.finish();

        let mut st = self.state.lock().await;
        let alive = match st.child.as_mut() {
            Some(child) => matches!(child.try_wait(), Ok(None)),
            None => false,
        };
        if alive && st.config_hash == hash {
            return false;
        }

        if let Some(mut child) = st.child.take() {
            child.kill().await.ok();
            if alive {
                info!("Camera set changed, restarting go2rtc");
            } else {
                warn!("go2rtc exited, restarting");
            }
        }

        if let Err(e) = write_private(&self.config_path, &config) {
            error!(path = %self.config_path.display(), error = %e, "Cannot write go2rtc config");
            return false;
        }

        let log = std::fs::File::create(&self.log_path)
            .map(std::process::Stdio::from)
            .unwrap_or_else(|_| std::process::Stdio::null());
        match Command::new(&self.bin)
            .arg("-config")
            .arg(&self.config_path)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(log)
            .kill_on_drop(true)
            .spawn()
        {
            Ok(child) => {
                st.child = Some(child);
                st.config_hash = hash;
                drop(st);
                // Give it a moment to bind before consumers connect.
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                info!(streams = cameras.len(), "go2rtc started");
                true
            }
            Err(e) => {
                error!(error = %e, "Failed to start go2rtc");
                false
            }
        }
    }

    pub async fn is_running(&self) -> bool {
        let mut st = self.state.lock().await;
        match st.child.as_mut() {
            Some(child) => matches!(child.try_wait(), Ok(None)),
            None => false,
        }
    }
}

fn yaml_str(s: &str) -> String {
    // JSON strings are valid YAML double-quoted scalars.
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".into())
}

fn percent_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => out.push(b as char),
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

/// The config can hold camera passwords, so keep it owner-only.
fn write_private(path: &std::path::Path, content: &str) -> std::io::Result<()> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)?;
    // `mode` only applies on creation; tighten a file left by an older run.
    f.set_permissions(std::os::unix::fs::PermissionsExt::from_mode(0o600))?;
    f.write_all(content.as_bytes())
}
