[package]
name = "open-nvr-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
open-nvr-domain = { path = "../domain" }
open-nvr-infrastructure = { path = "../infrastructure" }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
